services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: no
    environment:
      POSTGRES_DB: tickr
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tickr-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d tickr"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: tickr-api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tickr-backend
      - proxy_network

  promtail:
    image: grafana/promtail:2.9.3
    container_name: tickr-promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Use /config to avoid any image default at /etc/promtail
      - /opt/Tickr/backend/promtail:/config:ro
    command: -config.file=/config/promtail-config.yml
    networks:
      - tickr-backend

volumes:
  postgres_data:

networks:
  tickr-backend:
  proxy_network:
    external: true