spring:
  application:
    name: Tickr
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tickr}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
scheduler:
  reminder:
    poll-rate-ms: 10000
    sms_username: ${SMS_USERNAME}
    sms_password: ${SMS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,beans,env

