spring:
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    enabled: false
  api-docs: 
      enabled: false
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.tickr.tickr: WARN
